#include "lib.h"

#include <gtest/gtest.h>

#include <fstream>
#include <string>
#include <sstream>

TEST(Year2025, Day07) {
    const std::string test_1 = R"(.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............)";

    const std::ifstream input_file { "../input.txt" };
    std::stringstream input_stream;
    input_stream << input_file.rdbuf();

    EXPECT_EQ(year2025::day07::count_beam_splits(test_1), 21);
    EXPECT_EQ(year2025::day07::count_beam_splits(input_stream.view()), 1609);

    EXPECT_EQ(year2025::day07::count_beam_splits_quantum(test_1), 40);
    EXPECT_EQ(year2025::day07::count_beam_splits_quantum(input_stream.view()), 12472142047197);
}